### ISSUE TITLE
Version 3 broke functionality for IE11

### ISSUE THREAD

**Issue by mugliaa** [noppa/text-security#13]
I have noticed that since version 3 there is no longer support for the font within IE11. Things are working for me as usual within Chrome and Firefox. Reverting to v1.2.0 appears to fix the issue.

**Comment by noppa** [comment]
Are you experiencing the same as in #12?
Try changing the css a bit so that it loads only the "-compat" suffixed fonts, even for woff2.

**Comment by mugliaa** [comment]
My issue is a little different. The font does not render at all within IE for me. I'm just importing `text-security-disc.css` in my project. It might be possible to fix by loading fonts individually (haven't tried that yet) but i was hoping the CSS file would be sufficient.

**Comment by mugliaa** [comment]
Although now that you mention it I do also see the same behavior as #12 in Edge.

**Comment by noppa** [comment]
> i was hoping the CSS file would be sufficient

That's definitely how it should work, yes :) It's just that I'm not actually able to reproduce this myself - for me IE loads the compatibility eot font like it should - so I'd be interested to know if it's loading the non-compatibility woff2 font for you for some reason and then failing to actually display it correctly and if switching to compatibility version helps.

In the end, if the non-compatibility font is the problem for all these issues, I'll probably have to change the defaults for the css so that it just loads the compatibility fonts for all browsers. I'm just a little reluctant to do that without some more experimentation because the non-compatibility font weighs quite a bit less than the compatibility font and works fine in Firefox and doesn't cause problems in IE & Edge on my machine 🤷
