### ISSUE TITLE
Build is breaking in latest version.

### ISSUE THREAD

**Issue by nsisodiya** [noppa/text-security#16]

**Comment by noppa** [comment]
Do you mean building from source with docker is not working? What kind of error are you getting? Works fine for me at least on Fedora with podman, so I can't really say what could be wrong without more info

**Comment by noppa** [comment]
Thanks for the info, I tried with a small webpack demo but wasn't able to reproduce the issue [noppa/text-security-webpack-demo](https://github.com/noppa/text-security-webpack-demo)
do you notice some notable differences between that demo and your setup?

**Comment by green-pigeon** [comment]
This happens on both Windows and Linux with text-security version 3.2.0. It is a vuejs application created with vue-cli version 3.11.0. In main.js file I'm doing 
import Vue from 'vue';
import 'text-security/text-security-disc.css';
And that's where the build is breaking.
I tried your demo build and it's working, so maybe the problem is that I'm running a vuejs app.
"npm run dev" is the same as "npx vue-cli-service serve".

**Comment by noppa** [comment]
@green-pigeon Thanks, I was able to repro the issue with vue-cli 3.11.0. It seems that the postcss version that it uses wasn't able to handle `@supports (selector( .. ))` construct that was in the CSS. I replaced it with a bit simpler `-moz-appearance:meter` check to detect Firefox. Try version 3.2.1 and reopen if the build still fails.

**Comment by green-pigeon** [comment]
I confirm it is fixed. Thank you!
