### ISSUE TITLE
Not working on Firefox 90

### ISSUE THREAD

**Issue by green-pigeon** [noppa/text-security#20]
"text-security": "^3.2.1",

![image](https://user-images.githubusercontent.com/7714689/126756870-620fb2c7-be2e-4bcd-b594-b6dd283c1af1.png)

![image](https://user-images.githubusercontent.com/7714689/126756988-253899d1-84df-45ba-967d-bd59640f759c.png)

![image](https://user-images.githubusercontent.com/7714689/126757128-79787b61-8216-4286-be30-13e4aafd70e2.png)

**Comment by noppa** [comment]
Has the font loaded correctly (check the Network tab from console)?   
Firefox doesn't understand `-webkit-text-security: disc`, that's expected and fine, the property is there just for Webkit-based browsers.

**Comment by green-pigeon** [comment]
![image](https://user-images.githubusercontent.com/7714689/126764754-11a0af02-3c72-4e7b-b71a-557b849103dd.png)

But in the console there is a warning:
![image](https://user-images.githubusercontent.com/7714689/126764800-88359526-590f-4ad9-bcf3-22c6a0330203.png)

**Comment by noppa** [comment]
There's something wrong with your Express configuration, it's responding with `Content-Type: text/html` when it should be `text/css`. Most likely that's because it's not finding the css file and the html response is a 404 html page.
I can't really help with that without seeing your express config & file structure, but a few things you might want to check are
* Have you correctly installed the library, is the node_modules/text-security/text-security.css file actually there?
* Have you configured Express to serve node_modules files, e.g. with `app.use('/node_modules', express.static(__dirname, '/node_modules')`?
* Are you able to load any files, JS scripts, CSS, etc from node_modules, is the issue just with this one file or is it broken for all files in node_modules?

**Comment by green-pigeon** [comment]
I am working on vuejs. I have added this line in my index.html file:
`<link href="node_modules/text-security/text-security.css" rel="stylesheet" type="text/css">`
Now instead of the above line I added to my main.js file:
`import "text-security/text-security.css"`
And now it works. Strange but on Chrome it works without even importing the css.
Thanks for the quick answers!

**Comment by noppa** [comment]
Yeah on Chrome (which ~~is~~ _used to be_ a Webkit-based browser), it works because of the [`-webkit-text-security`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security), it doesn't even need to load the font.

The point of this font is to bring `-webkit-text-security` to other browsers, like Firefox :)   
Glad you got it working
