### ISSUE TITLE
Cover CJK

### ISSUE THREAD

**Issue by MilanCancarevic** [noppa/text-security#4]
Can we use this font to cover CJK chars?
Right now:
[某人]真够朋友

would mask it as:
x某人x真够朋友

**Comment by noppa** [comment]
The problem with CJK the sheer amount of them. Right now the fonts are generated with very simple unicode character - glyph mappings and generating tens of thousands of those.

I have been looking into "abusing" missing character glyphs in the fonts so that the browser would show the dot glyph for _any_ character, but haven't gotten far with that approach yet.

If I may ask, what's the use case for this?  
This font was [originally created to sove a very specific problem](https://stackoverflow.com/questions/36935576/how-to-make-input-type-tel-work-as-type-password/36950075#36950075) with `input[type=tel]` elements, so I don't quite see where you'd need to mask CJK characters and couldn't just use `input[type=password]`.

I noticed you also opened kylewelsby/dotsfont#7  
If kylewelsby wants to collaborate on this, that would be awesome 😄

**Comment by MilanCancarevic** [comment]
@noppa 
use case would be:
i want browser to prevent autosave on user/pass when logging in due to regulations of PHI (personal health info) so instead of type=password i wanted to use other input/textarea and mask values with dotted font, right now fixes and workarounds  like autocomplete=off are not fully supported in browsers so i tried this option.

**Comment by noppa** [comment]
Ah right. I have previously had good luck with [this approach](https://stackoverflow.com/a/25111774/6184698) for that sort of thing. That is, using a hidden password field in the page in addition to the main password field.

**Comment by noppa** [comment]
I've been looking into [Adobe's notdef font](https://github.com/adobe-fonts/adobe-notdef) and how they do it. Haven't gotten far yet, but there is some hope that I'll get this issue resolved some day.

**Comment by noppa** [comment]
Good news!  
It looks like this issue will (finally) get resolved soon.  
I have an experimental support for modest 1,111,998 unicode code points coming in [version 2](https://github.com/noppa/text-security/tree/version-2). That should easily cover CJK.

There's still al lot of stuff missing; currently that branch only has the "disc" glyph and only a `.woff`` font file is generated. But if you are eager to try it out (disc glyph is the one that normal password fields use and woff files are widely supported anyways), you can install the new alpha version with 
```sh
npm i text-security@alpha
```

Note that I also changed the file paths a bit, the generated css and font files are now in the root directory, not in _dist_. See [the installation section](https://github.com/noppa/text-security/tree/version-2#installation) in the readme of version 2 branch.

Everything seems to work well in Windows 10 Chrome & Firefox (although FF did have some styling issues with the input field, but I'm sure that's easy to fix), I haven't had the chance to test in other devices yet.

**Comment by stavalfi** [comment]
I confirm that v2 is working great and convert Hebrew characters to * (mac + Firefox 66.0.1 (64-bit), Chrome 72.0.3626.121).

**Comment by noppa** [comment]
I'm happy to announce that, after almost two years, this issue can finally be closed.

Just published version 3 supports all unicode characters, works in IE _and_ for modern browsers it has **smaller** bundle size than version 2 had.

If you are still using this library after this long wait, you should check it out :)
